fix
AstarNetwork/astarbase pull request #24
Opened 2022-04-20 09:53 UTC by niklabh

2022-04-20 18:19 UTC, Maar-io requested changes
please update contract version as well.
Before we merge this it would be good to tag with version v1 and network name to keep track what was deployed on the Astar/Shiden/Shibuya

2022-04-21 16:22 UTC, Maar-io commented
@niklabh please make PR against main branch

2022-04-21 16:53 UTC, niklabh commented
First this PR needs to be merged https://github.com/AstarNetwork/astarbase/pull/23

2022-04-21 16:58 UTC, Maar-io commented
@niklabh all contract changes need to be for main branch as well

2022-04-25 10:05 UTC, Maar-io requested changes
Please first rebase contract on main and than add your changes

2022-04-25 10:05 UTC, Maar-io commented on contract/contracts/AstarBaseV3.sol
> +contract AstarBaseV3 is Initializable, OwnableUpgradeable {
it is V2

2022-04-25 10:07 UTC, merged